### ISSUE TITLE
Plugin MentionPlayer v3.0.0 generated an exception while executing task 60

### ISSUE THREAD

**Issue by eaeniko** [Triozer/spigot-mention-player#3]
```
20.03 15:11:06 [Server] Craft Scheduler Thread - 18/WARN [MentionPlayer] Plugin MentionPlayer v3.0.0 generated an exception while executing task 60
20.03 15:11:06 [Server] INFO java.lang.NullPointerException: Nodes must be provided.
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:306) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:06 [Server] INFO at fr.triozer.mentionplayer.api.player.MPlayer.save(MPlayer.java:213) ~[?:?]
20.03 15:11:06 [Server] INFO at fr.triozer.mentionplayer.api.player.MPlayer.<init>(MPlayer.java:55) ~[?:?]
20.03 15:11:06 [Server] INFO at fr.triozer.mentionplayer.api.player.MPlayer.get(MPlayer.java:97) ~[?:?]
20.03 15:11:06 [Server] INFO at fr.triozer.mentionplayer.listener.CacheListener.lambda$onLogin$1(CacheListener.java:26) ~[?:?]
20.03 15:11:06 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
20.03 15:11:08 [Multicraft] Skipped 4 lines due to rate limit (30/s)
```

**Comment by triozer** [comment]
@NikolaiCinotti can you send your `config.yml` ? Do you use other plugins ?
